# Generated by Django 2.1.3 on 2018-11-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='slug',
            field=models.SlugField(default='farazuddin'),
            preserve_default=False,
        ),
    ]
