# Generated by Django 2.1.3 on 2018-11-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_students_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='S_email',
            field=models.EmailField(blank=True, default='farazuddin.m17@iiits.in', max_length=254),
        ),
    ]
