# Generated by Django 2.1.3 on 2018-11-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_students_s_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='S_password',
            field=models.CharField(default='password123', max_length=50),
            preserve_default=False,
        ),
    ]
