# Generated by Django 2.1.3 on 2018-11-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_students_s_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='S_email',
            field=models.EmailField(max_length=254),
        ),
    ]
