# Generated by Django 2.1.3 on 2018-11-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_students_s_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='S_grade',
        ),
    ]
