# Generated by Django 2.1.3 on 2018-11-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_remove_students_s_grade'),
        ('Student', '0004_auto_20181117_1544'),
    ]

    operations = [
    ]
