# Generated by Django 2.1.3 on 2018-11-17 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_merge_20181118_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('C_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('C_name', models.CharField(max_length=15)),
                ('C_credits', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='S_email',
            field=models.EmailField(blank=True, default='farazuddin.m17@iiits.in', max_length=254),
        ),
        migrations.AddField(
            model_name='students',
            name='S_courses',
            field=models.ManyToManyField(to='Student.Courses'),
        ),
    ]
