# Generated by Django 2.1.2 on 2018-11-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_auto_20181118_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='S_pro',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
