# Generated by Django 2.1.3 on 2018-11-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_auto_20181117_1544'),
        ('Teacher', '0003_teachers_t_password'),
    ]

    operations = [
    ]
